### ISSUE TITLE
Problemas com caracteres especiais

### ISSUE THREAD

**Issue by lawrencestfs** [diogosmendonca/webdep#1]
Pessoal, como estamos usando sistemas operacionais diversos, acredito que poderemos ter problemas com caracteres especiais. Na verdade, já tive problemas com a documentação de algumas classes, que tiveram caracteres substituídos pelo replacement do unicode (�).

Como solução sugiro não utilizarmos acentuação, ou então, podemos gerar a documentação em inglês. Outra solução ainda seria padronizarmos um encoding, mas acredito que demandaria um trabalho de configuração. O que vocês acham, possuem alguma sugestão?

**Comment by RianTavares** [comment]
Verdade!
Bom eu votaria em não utilizarmos pontuação mesmo.

**Comment by luanvilarim** [comment]
Uma solução pra isso seria mudar o charset do projeto e dos arquivos manualmente. Se não me engano está em Cp-1052 e teriamos que passar pra UTF-8, mas é uma mudança que envolve vários arquivos e acho que seria melhor ter o Diogo envolvido.
