### ISSUE TITLE
Galera o que eu faço ?

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#10]
Eu estou tentando dar pull, mas vem esse aviso , já olhei é uma mudança que o professor fez eu dou checkout ? 

![image](https://cloud.githubusercontent.com/assets/4684228/20549354/92dbead2-b112-11e6-8b72-ca3f5e7adb7c.png)

**Comment by OliveiraNt** [comment]
Veja se as modificações que você está fazendo não interferem nas do professor, se não é só fazer um merge da sua com a dele,  caso de conflito salva o que você fez separado do projeto(só pra não se perder)  desfaz o que você modificou,  atualiza o projeto com a versão mais recente e tenta encaixar as suas modificações nela
