### ISSUE TITLE
Escolha do sistema na tag do navbar

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#12]
Olá pessoal, 
no navbar existe uma tag customizada que está já funcionando, ela lista os sistemas vinculados aos usuários, pelo que eu reparei além de uma tela que ficamos acho que outros também vão usá-la para um preenchimento automático dos campos, eu estou tentando uma solução aqui onde eu pegaria através de uma javascript e faria um post . Vocês veem outra abordagem ?

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">

<title>Insert title here</title>
</head>
<body>
	
	<script type="text/javascript">
	
		function post(path, params, method) {
    method = method || "post"; // Set method to post by default if not specified.

    // The rest of this code assumes you are not using a library.
    // It can be made less wordy if you use one.
    var form = document.createElement("form");
    form.setAttribute("method", method);
    form.setAttribute("action", path);

    for(var key in params) {
        if(params.hasOwnProperty(key)) {
            var hiddenField = document.createElement("input");
            hiddenField.setAttribute("type", "hidden");
            hiddenField.setAttribute("name", key);
            hiddenField.setAttribute("value", params[key]);

            form.appendChild(hiddenField);
         }
    }

    document.body.appendChild(form);
    form.submit();
}

		function pegarID(){
		//post('/contact/', {name: 'Johnny Bravo'});

		post('#',{idsistema:document.getElementById("mySelect").selectedIndex},'get');
	

		
		}
	
	</script>
	<select id="mySelect" >
		<option value="void" id="1" onclick="pegarID();">Choose your answer</option>
		<option value="To measure time" id="2" onclick="pegarID();">To measure time</option>
	
	</select>

</body>
</html>

**Comment by diogosmendonca** [comment]
Não entendi muito bem qual o problema. Quando você diz "preenchimento
automático dos campos" é em que evento? onchange do select? Você pode
associar um evento ao select e tratá-lo com uma função javascript. Se
precisar disto basta adicionar um parâmetro a tag customizada. Se for isto
mesmo confirma que te ajudo a fazer.

abs,

Diogo.

Em 24 de novembro de 2016 21:26, Felipe Mello <notifications@github.com>
escreveu:

**Comment by drinith** [comment]
Professor,
tem uma tela que o Marcelo parece que estava precisando que o id do sistema
já viesse, então eu fiz esse teste no Javascript, estou fazendo uma
submissão do id e depois capturando ele é jogando na sessão quando
ocorresse a troca de telas, mas eu estava pensando no código da tag, se
fosse acrescentado ali quando ela printa um código que esse valor fosse
jogado na sessão funcionaria?

Att,

Felipe Mello

Em 25/11/2016 09:20, "Diogo Silveira Mendonça" <notifications@github.com>
escreveu:

**Comment by lawrencestfs** [comment]
Prezados,

Como sabem, eu estou cuidando do login, e agora fiquei com uma dúvida com relação a essa variável de sessão. Esse id deve ser setado na index.jsp ou na Command de autenticação? E que valor ele deve receber?

Eu estava setando o id no AuntenticaUsuarioCommand, utilizando um request.getSession().setAttribute(), e passando o id do Usuário (salvo no banco de dados). Está correto? Se estiver errado, poderiam me orientar nas correções, por favor?

PS: Eu e o Rian estavamos tendo problemas com a navbar. Removendo a autenticação da navbar, meu login funciona, mas acredito que não esteja setando corretamente o atributo de sessão id.
[]s

**Comment by diogosmendonca** [comment]
Eu acho melhor no Command,

Abs,

Diogo.

Em 25 de novembro de 2016 12:28, Lawrence Fernandes <
notifications@github.com> escreveu:

**Comment by lawrencestfs** [comment]
@drinith  
Felipe,

Percebi agora que as verificações na sua navbar estão utilizando uma Command chamada ObterUsuario, que me parece extremamente incompleta/incorreta. Só para ter uma ideia, tem uma pergunta nela!

Acredito que todo o processamento para autenticação e concessão de permissão ao usuário deve passar pela AutenticaUsuarioCommand, visto que essa etapa de login ficou a cargo do meu grupo. Eu não tinha me atendado com relação às permissões do usuário, vou precisar editar isso. Se você souber e tiver condições, pode fazer as correções direto nela. Precisando de ajuda, só falar comigo. Vou ver o que posso fazer aqui.

[]s
