### ISSUE TITLE
Problema para acessar e testar páginas

### ISSUE THREAD

**Issue by RianTavares** [diogosmendonca/webdep#13]
Galera preciso visualizar os JSP's do meu projeto para trabalhar, porém agora que o sistema de login está no repositório, toda vez que tento rodar ele pede usuário e senha. 
Já populei a tabela usuário no banco e quando tento acessar na página de login nada ocorre. 
Vocês estão enfrentando o mesmo problema? 
e alguém sabe como eu poderia resolver?

**Comment by MarcelloSerqueira** [comment]
Eu removi o include do navbar.jspf que fica no body e parou de ficar solicitando o login e senha

**Comment by RianTavares** [comment]
Putz, boa! Eu estava tentando tirar as condições do navbar e tudo mais. 
Fiz isso e rodou de boa aqui.
Obrigado!
