### ISSUE TITLE
UsuarioServices

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#14]
Pessoal, 
acho que eu criei essa class e no início eu não reparei que ela ficou sem o "s" , eu vi que mudando eu mexo  com uma declaração da Class InsertPadraoURLCommand , posso mexer lá ?

**Comment by luanvilarim** [comment]
Pode, o lawrence tinha renomeado a UsuarioService pra UsuarioServices, mas não sei porque de vez em quando não funciona.

**Comment by lawrencestfs** [comment]
Opa, realmente, eu tinha editado isso no meu projeto, mas me confundi e sem querer acabei mudando no repositório também.

Aqui no meu projeto, pelo que me lembro, as referências foram atualizadas automaticamente. A não ser que alguma jsp esteja chamando a classe, ai teria que mudar manualmente.

Luan, poderia me dizer o que não está funcionando, para eu corrigir?
