### ISSUE TITLE
Diogo, é possível setar os acessos dentro de Sistema pra dar Delete Cascade ao apagar um Sistema?

### ISSUE THREAD

**Issue by luanvilarim** [diogosmendonca/webdep#15]
Estou com problemas pra deletar um sistema quando há um RegistroLogAcesso associado a ele. Na verdade, meu problema está em buscar os Registros de acesso que estão relacionados a um sistema. Eu recebo um erro do Hibernate na busca dizendo:

Could not deserialize 

Eu tentei fazer a busca colocando o objeto Sistema na busca, com TypedQuery(dá o erro acima), tentei colocar o id do sistema na busca(dá erro de tipo incompatível). O erro de incompatibilidade diz que tenho um Long e estou passando um Long. Aí fiquei preso nisso.

Por isso estou sugerindo delete cascade porque teoricamente, ele iria deletar todos os registros de log de acesso associados ao sistema que se quer deletar.  Caso seja uma possibilidade, eu só não sei como fazer(@CascadeType.DELETE?).

**Comment by luanvilarim** [comment]
@OneToMany(mappedBy="sistema", orphanRemoval=true, cascade=CascadeType.ALL)

Ainda depois de usar estes parametros nos RegistrosLogAcesso e outros campos que tem relacionamento com Sistema não consigo deletar o sistema que possui relacionamento com essas entidades:

RegistroLogAcesso
RegistroLogErro
Permissoes
Versoes

Recebo o seguinte erro

:javax.persistence.PersistenceException: org.hibernate.type.SerializationException: could not deserialize

**Comment by diogosmendonca** [comment]
Oi Luan,

Da uma olhada nestes links, eles devem ajudar. Lembre-se de dropar o banco todo e gerar novamente ele zerado para que funcionem as alterações nos Entities do JPA (ele não faz update do modelo direito em diversos casos):

http://stackoverflow.com/questions/25967935/jpa-hibernate-spring-onetomany-delete-cascade
http://stackoverflow.com/questions/7197181/jpa-unidirectional-many-to-one-and-cascading-delete
http://fruzenshtein.com/bidirectional-many-to-one-association/

**Comment by luanvilarim** [comment]
Oi Diogo,

Realmente não lembrei de dropar o banco. Vou tentar isso e ler esse links. Aí dou um feedback.

Obrigado.

**Comment by luanvilarim** [comment]
Consegui fazer a remoção do Sistema 1. As alterações que fiz foram:

- Sistema.java
`@OneToMany(mappedBy="sistema", cascade=CascadeType.REMOVE)
private List<Versao> versoes; `
	
`@OneToMany(mappedBy="sistema", cascade=CascadeType.REMOVE)
private List<Permissao> permissoes;`
	
`@OneToMany(mappedBy="sistema", cascade=CascadeType.REMOVE)
private List<RegistroLogAcesso> acessos;`

`@OneToMany(mappedBy="sistema", cascade=CascadeType.REMOVE)
private List<RegistroLogErro> erros; `

- RegistroLogAcesso.java(e filhos de Sistema.java):
`@ManyToOne
@JoinColumn(name="acessos")
private Sistema sistema;`

Vou deixar o issue aberto por enquanto pra caso eu ache mais algum erro em relação à isso

**Comment by diogosmendonca** [comment]
Que bom! Seria legal atualizar logo todas as relações nas entidades para
que ninguém mais tenha este problema. Poderia fazer?

Precisou atualizar o pom.xml para o hibernate-java8?

Abs,

Diogo.

Em 3 de dezembro de 2016 10:37, luanvilarim <notifications@github.com>
escreveu:

**Comment by luanvilarim** [comment]
Na verdade, analisando os scripts do banco não estou certo de que o problema foi resolvido. Olhando os scripts do banco depois de dropar, o que aconteceu foi que foi retirado da tabela dos filhos a coluna SISTEMA_ID. Por isso que a exclusão foi possível. 

Não atualizei o pom.xml

**Comment by luanvilarim** [comment]
Agora sim Diogo, faltou refazer os setters dos relacionamentos. Usei este link pra me ajudar:
http://stackoverflow.com/questions/13370221/jpa-hibernate-detached-entity-passed-to-persist

Fiz um teste atribuindo Permissão e LogErro a um sistema e a deleção foi bem sucedida
