### ISSUE TITLE
Texto caractere estranho

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#17]
Olá pessoal, 
mesmo alterando no windows tudo para UTF-8 e nada no Message aparecer com outro caractere , no navegador ainda aparece algumas coisas distorcidas , alguém já conseguiu resolver isso ?

Att, 

Felipe Mello

**Comment by lawrencestfs** [comment]
Sim, resolvi esse problema no modal do logout. Reparei que as chamadas para as mensagens estavam "quebradas". Compare cuidadosamente as chamadas das mensagens e o que consta no resource bundle, provavelmente é isso.

**Comment by drinith** [comment]
Como nos falamos depois pelo face, não era essa questão que estava abordando, era as mensagens que aparecem no messages. Acabei de instalar o Linux aqui para testar a diferença, e reparei , que nele o padrão tb é o ISO-8859-1 , então ele distorceu tudo, quando passei ele para UTF-8 ele ficou correto novamente, contudo as páginas aparecem com o erro como nas telas de teste do Rafael, então quando eu copie o texto certo em UTF-8 e voltei para o padrão ISO-8859-1, no linux as páginas rodaram sem erros .

![captura de tela de 2016-11-30 23-37-06](https://cloud.githubusercontent.com/assets/4684228/20778638/3956d7ca-b756-11e6-94f4-b9e16bdb4967.png)


Teste do Rafael
![image](https://cloud.githubusercontent.com/assets/4684228/20778695/a492fe24-b756-11e6-8ae3-3526add9a852.png)

**Comment by drinith** [comment]
No windows notei que acontece a mesma coisa, como teste eu copie o arquivo com o texto correto , passei ele de UTF-8 para ISO-8859-1 , o arquivo ficou todo errado , colei o texto correto , então quando rodei voltou as páginas rodarem sem erros . 

![image](https://cloud.githubusercontent.com/assets/4684228/20779482/e472231c-b75b-11e6-8f9b-fb4bdc22bc42.png)

**Comment by lawrencestfs** [comment]
Felipe,
Não entendi como ficou, você conseguiu rodar a página index sem problemas de encoding? Após pesquisar, resolvi inserir uma tag HTML <meta> na página, para certificar que browsers antigos não alterem o encoding. Me diga se agora está funcionando, por favor.

Pessoal,
Caso algum de vocês esteja com problemas no encoding, certifiquem-se de estar usando a última versão dos message bundle. Verifiquem se o projeto e os arquivos estão em UTF-8. Em último caso, limpem o cache do tomcat para ver se surte efeito.

Professor,
Pesquisando, me deparei com a opção de incluir a configuração do encoding de todas as páginas jsp via declaração no web.xml. Seria uma boa abordagem, ou não? A declaração é a seguinte:
```
<jsp-config>
    <jsp-property-group>
        <url-pattern>*.jsp</url-pattern>
        <page-encoding>UTF-8</page-encoding>
    </jsp-property-group>
</jsp-config>
```

**Comment by drinith** [comment]
O index ficou certo aqui quando voltei para o encoding original do windows, também encontrei indicações do web.xml , mas não fez efeito no windows, minha preocupação é que alguns testadores estão usando o windows e o projeto pra eles também está aparecendo  distorcido
