### ISSUE TITLE
Valores de perfil do usuário

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#18]
Olá @lawrencestfs , 
é só para confirmar, muitos dos testes do Rafael , pelo que eu notei falharam, pois com o perfil ele não tinha acesso a determinados links na barra de menu , então fazendo as inserções do cadastro de usuário de vocês notei que já estão começando com a letra maiúscula, tipo "Administrador" , "Analista", está assim né ? 

Tela do Rafael onde ele não conseguiu ver nenhum dos itens do menu
![image](https://cloud.githubusercontent.com/assets/4684228/20779034/09d96e74-b759-11e6-959e-b01026ac41cb.png)

**Comment by lawrencestfs** [comment]
Felipe, não entendi a sua pergunta. Você ainda está com esse problema?

Testei aqui a última versão do sistema, com os dois tipos de permissão de usuário, e fui capaz de acessar corretamente o home e a navbar - conforme a permissão do usuário.

![teste1](https://cloud.githubusercontent.com/assets/13123535/20803421/5145da7c-b7d6-11e6-953c-05cc6b5a7f46.png)
![teste2](https://cloud.githubusercontent.com/assets/13123535/20803426/5441cf06-b7d6-11e6-93d2-718fa6f94d90.png)

**Comment by drinith** [comment]
Aqui está funcionando, era só mais para confirmar .
Obrigado .

**Comment by lawrencestfs** [comment]
A sim, agora vendo na sua mensagem inicial entendi. Valeu por avisar, deve ser problema com a versão do sistema que usaram no teste. Vou fechar a issue então.
