### ISSUE TITLE
run-database.bat Classe Não encontrada

### ISSUE THREAD

**Issue by luanvilarim** [diogosmendonca/webdep#2]
Eu estou tentando rodar o projeto e estou com erros em todos os smoke tests por causa do banco. Quando tento rodar o banco recebo esse erro: 

Error: Could not find or load main class org.hsqldb.server.Server

Alguém conseguiu rodar? Preciso fazer mais alguma coisa além de rodar o .bat do projeto?

**Comment by diogosmendonca** [comment]
Atualizei o .bat, no meu windows funcionou corretamente. Agora tem que
rodar um mvn install pelo menos uma vez antes porque senão não baixa o .jar.

Abs,

Diogo.

2016-11-12 14:27 GMT-02:00 luanvilarim notifications@github.com:

**Comment by luanvilarim** [comment]
Obrigado Diogo. Agora rodaram 11/12 testes, o Selenium foi o único que parou:

Tests in error: 
  openPageSelenium(br.cefetrj.webdep.tests.smoke.SeleniumSmokeTest): org.apache.http.conn.HttpHostConnectException: Connect to localhost:30091 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect(..)

**Comment by lawrencestfs** [comment]
Estou obtendo o mesmo erro ao rodar run_database.sh:

Error: Could not find or load main class org.hsqldb.server.Server

Tentei editar o arquivo confome o .bat, atentando para as barras, mas não funcionou.

**Comment by diogosmendonca** [comment]
Executou o mvn install antes? se não tiver funcionando no seu caso você vai
ter que encontrar onde está o hsqldb.jar na sua máquina e editar o .bat
para que o caminho corresponda. Coloquei o caminho típico do maven no
windows que é no diretório do usuário o diretório .m2, agora se está em
outro lugar na sua máquina ai tem que procurar. ok?

O problema do smoke test no windows foi resolvido.

Abs,

Diogo.

2016-11-12 15:48 GMT-02:00 Lawrence Fernandes notifications@github.com:

**Comment by lawrencestfs** [comment]
Sim, executei o mvn install primeiro. Estou usando linux. Tentei editar no .sh o caminho para a pasta onde o hsqldb.jar está, mas não funcionou. Consegui rodar o banco indo até o diretório e executando manualmente o comando.

Para quem estiver com o mesmo problema:
1. Vá até o diretório onde baixou/descompactou o hsqldb. Se não encontrar: find / -name 'hsqldb-2.3.1'
2. cd hsqldb-2.3.1/hsqldb/lib
3. java -cp hsqldb.jar org.hsqldb.server.Server --database.0 database/webdep --dbname.0 webdep

Agora tive problemas com o smoke test. Tentei rodando o mvn e o JUnit test. Parece que ele não foi capaz de carregar o index.jsp, acho que o problema é com o Firefox. Tem como eu configurar outro navegador para o teste?

**Comment by diogosmendonca** [comment]
Lawrence,

O servidor Tomcat deve estar ligado para o smoke test do Selenium
funcionar. Basta ir no eclipse e colocar run on server antes de rodar os
testes.

Que bom que conseguiu resolver os problemas, achei que você estava usando
windows.

abs,

Diogo.

Em 12 de novembro de 2016 17:22, Lawrence Fernandes <
notifications@github.com> escreveu:
