### ISSUE TITLE
Aviso de necessidade de dropar o banco

### ISSUE THREAD

**Issue by luanvilarim** [diogosmendonca/webdep#22]
Pessoal, tive que habilitar um CASCADE DELETE ao apagar um Sistema e refazer alguns dos relacionamentos entre o Sistema e as entidades Permissao, RegistroLogAcesso, RegistroLogErro e Versao.

Então aconselho que dropem o banco e criem de novo para que as alteraçoes tenham efeito. Não quero alterar os arquivos de script do banco aqui no git pra não complicar vocês localmente.

Pra dropar o banco:
- Fazer backup da pasta src/main/resources/database(renomeie para database_old,por exemplo)

- Executar o arquivo run_gerenciador e rodar com as configurações abaixo:
![2016-12-03 1](https://cloud.githubusercontent.com/assets/23281140/20862015/3732e1b4-b986-11e6-85c7-233d58f16891.png)

-Executar o arquivo run_database
-Executar o projeto e tentar submeter o login. Vai dar erro, obviamente, mas faz com que o banco seja gerado conforme as Annotations das entidades do projeto.

BACKUP
- Caso queira recuperar os dados que estavam no banco, vá em database_old/webdep.script e encontre os INSERTs referentes aos seus dados. Note que algumas tabelas mudaram, portanto faá as alterações necessária na query.
-Execute o arquivo run_gerenciador novamente, só que como Server:
![2016-12-03 2](https://cloud.githubusercontent.com/assets/23281140/20862034/0322282a-b987-11e6-9d6f-276f01404b7f.png)

-Copie e cole as queries e execute:
![2016-12-03 3](https://cloud.githubusercontent.com/assets/23281140/20862040/3bbc0156-b987-11e6-803d-6a7c93b75d28.png)

Qualquer dúvida, ou bug, comente abaixo.

Abraço

**Comment by RianTavares** [comment]
Quando eu tento rodar o projeto pra submeter  o login errado :
![captura de tela 76](https://cloud.githubusercontent.com/assets/8935295/20862599/f1b6191a-b996-11e6-81b1-36ef2391ce7c.png)

**Comment by RianTavares** [comment]
Quando eu tento rodar o projeto para submeter o login errado: 
![captura de tela 77](https://cloud.githubusercontent.com/assets/8935295/20862602/070a71d0-b997-11e6-80a9-03dbb15a22e1.png)
