### ISSUE TITLE
Combobox de padrões de URL

### ISSUE THREAD

**Issue by mdevino** [diogosmendonca/webdep#23]
Preciso da combobox de padrões de URL para proseguir com minha parte, onde posso encontrá-la?

**Comment by luanvilarim** [comment]
Tá lá na página HTTPreport.jsp

**Comment by mdevino** [comment]
Ela já está pronta? Eu tinha entendido que ela já traria as URLs todas.

**Comment by luanvilarim** [comment]
Cara, então, eu sou responsável somente pela combobox que mostra os padrões URL do banco, o resto se não me engano o @drinith é parte do grupo responsável pelo resto da página. Ontem eu subi a combobox pronta, se tu povoar teu banco com os registros de log acesso vai funcionar. 

Lembrando tb que a combobox de Sistema no navbar tá usando o método change pra jogar o id do sistema na sessão, e eu estou usando esse id. Pra evitar que dê um NullPointerException, seleciona o sistema na navbar e recarrega a página que os padrões de URL relacionados aos Registros de Log daquele Sistema irão aparecer.

**Comment by mdevino** [comment]
Eu estava me referindo à combobox mesmo, não à página. Mas se já está buscando as URLs no banco já consigo fazer minha parte. Obrigado.
