### ISSUE TITLE
Ao grupo que fez a DropDownList do Sistema na navbar

### ISSUE THREAD

**Issue by luanvilarim** [diogosmendonca/webdep#25]
Tenho a impressão de que o Sistema selecionado só é colocado na sessão após o evento change da dropdown list. Isso traz alguns erros em buscas dependentes dessa informação, pois o Sistema aparentemente está selecionado, mas nunca foi pra sessão, seria necessário reselecionar o sistema.

Ainda não estou 100% certo de que isso está afetando algumas buscas no banco fazendo com que elas só aconteçam 'de segunda', pois sempre que, após resetar o Tomcat e selecionar o Sistema as buscas passam a ser feitas 'de primeira'. Mas definitivamente afeta a busca de padrão URL pois preciso saber o sistema selecionado e o mesmo só vai pra sessão após reselecionar na navbar

. Ofereço ajuda pra resolução deste problema, pois enfrentei algo semelhante na hora de fazer o cadastro de Sistema.

**Comment by drinith** [comment]
Em relação a navbar por estar usando ajax e não dar refresh na página,
parece que nada ocorre, contudo ele até é mantido selecionado mesmo quando
acontece um refresh forçado, justamente por que ele é colocado na sessão e
também então é usado para apontar a opção selecionada.

Att,

Felipe Mello

Em 6 de dezembro de 2016 14:23, luanvilarim <notifications@github.com>
escreveu:

**Comment by luanvilarim** [comment]
Aconselho a deixar um campo vazio antes de todos os sistemas listados no combobox de Sistema, pois ao entrar a página HTTPreport a primeira coisa que se vê é um erro pedindo para selecionar um Sistema. Isso é porque sempre que tentamos requerir da sessão o id do sistema ele vem nulo. E depois de selecionar, isto é , depois do change do <select>, aí sim o sistema vai pra sessão. Pode se usar também o Command que busca esses Sistema e manda pra o select para setar o id na sessão.
