### ISSUE TITLE
Como descobrir quem é o usuário logado para administrar as permissões e cadastrar Padroes URL?

### ISSUE THREAD

**Issue by luanvilarim** [diogosmendonca/webdep#3]
Pelo que entendi, o Servidor possui vários Sistemas, cada Sistema possui várias Permissões e cada Permissão possui um Usuário. Na parte de Padrão de URL, será necessário um usuário para ser dono desse padrão. Cada RegistrodeLogAcesso possui um usuário. Ao retirar do banco a lista de logs, receberei todos os usuários cadastrados no sistema ou somente o usuário daquele login no servidor(ou aquela instância do banco que é utilizada pelo usuário logado)?

**Comment by diogosmendonca** [comment]
Prezado,

As afirmações que você fez não batem com o modelo de dados. Segue ele em
anexo, lá estão descritas em UML as relações entre as entidades. Veja, cada
RegistroLogAcesso é de um Sistema somente. Um usuário pode ter permissão de
acesso a vários sistemas. Respondendo sua pergunta:

No banco estão todos os dados de todos os usuários, sistemas e registros de
log. Você irá filtrar  (usando JPQL) os registros de log do sistema
selecionado no menu. No menu só aparecem os sistemas que o usuário tem
permissão.

Abs,

Diogo.

Em 12 de novembro de 2016 19:24, luanvilarim notifications@github.com
escreveu:

**Comment by luanvilarim** [comment]
Obrigado Diogo! Tinha esquecido dos sistemas no menu.

**Comment by diogosmendonca** [comment]
O id do usuário logado estará na seção no atributo usuário. Você estava na
aula passada em sala? falamos disto lá.

Quanto ao e-mail anterior, se for em relação a filtragem dos padrões de url
não é com JPql como falei mas sim com expressões regulares.

abs,

Diogo.

Em 13 de novembro de 2016 11:06, Diogo Mendonça diogosmendonca@gmail.com
escreveu:
