### ISSUE TITLE
Atualização das classes Permissão e Usuário

### ISSUE THREAD

**Issue by lawrencestfs** [diogosmendonca/webdep#5]
Professor, na aula passada lembro de você mecionar que iria colocar a lógica de permissão dentro da entidade usuário, correto? Existe algum planejamento sobre quando essa mudança deve ser implementada?

**Comment by diogosmendonca** [comment]
Hoje, só que não de madrugada. De manhã.

**Comment by diogosmendonca** [comment]
Feito.
