### ISSUE TITLE
Pelo Amor de Jeová! Parem de subir arquivos de configuração da IDE e afins!

### ISSUE THREAD

**Issue by luanvilarim** [diogosmendonca/webdep#6]
Toda vez que alguém sobe algo eu recebo conflitos de .classpath e arquivos internos do eclipse que são automaticamente atualizados se vocês só subirem as classes e jsps. De 4 horas que eu trabalho passo 3 resolvendo conflitos que são de arquivos internos!

**Comment by RianTavares** [comment]
Pois é, o projeto não anda assim, galera!
Toda hora é um problema diferente e desnecessário...

**Comment by OliveiraNt** [comment]
Ao invés de perderem suas tardes inteiras resolvendo problemas que não foram vocês que causaram façam como o grande Bilu uma vez nos disse e busquem conhecimento

https://git-scm.com/book/pt-br/v1/Git-Essencial-Desfazendo-Coisas

**Comment by luanvilarim** [comment]
Conhecimento eu já tenho, esse issue é pra avisar a galera que não dá pra selecionar tudo e dar commit. Se todos tiverem cuidado funciona. Agora tb não é viável toda vez que rolar um commit eu ter que desfazer as ações pra me proteger de descuidos. É só dar commit no que mexeu(em sua própria parte, se for mexer no dos outros saiba o que está fazendo) e acabou, sem mistério. 

Sem falar que também mais impossível ainda é,com o prazo que temos, você oferecer um livro pra consertar tudo quando, com um pouco de cuidado, ninguém iria morrer e a gente evitaria issues como esse.

**Comment by diogosmendonca** [comment]
Quem desfez o meu commit???? Se começarmos a desfazer os commits dos outros este projeto não vai chegar no final. Eu depois vou analisar com calma o que vocês estão fazendo no git e se um está atrapalhando o trabalho do outro. A regra básica aqui é o seguinte, você só dá commit no que você está trabalhando e não desfaz o trabalho dos outros. Se houverem arquivos compartilhados tem que ter o dobro de atenção para não prejudicar o que os outros estão fazendo. Vou colocar os arquivos de .settings e .project do eclipse no gitignore assim cada um configura como quiser na sua máquina. Vou dar commit em tudo que foi desfeito e peço para não desfazerem mais os commits no git, a menos que  impactem somente no seus últimos commits (mandou coisa errada). Deu problema de merge, corrige e faz um novo commit.

**Comment by diogosmendonca** [comment]
Feito.
