### ISSUE TITLE
HTTP Status 500 - The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application type Exception report

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#7]
Olá pessoal, 
estou mexendo aqui no projeto e em duas máquinas que eu trouxe, estão dando exceções quando rodo a página está acontecendo com mais alguém ? 

HTTP Status 500 - The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
type Exception report

message The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application

description The server encountered an internal error that prevented it from fulfilling this request.

exception

org.apache.jasper.JasperException: The absolute uri: http://java.sun.com/jsp/jstl/core cannot be resolved in either web.xml or the jar files deployed with this application
	org.apache.jasper.compiler.DefaultErrorHandler.jspError(DefaultErrorHandler.java:55)
	org.apache.jasper.compiler.ErrorDispatcher.dispatch(ErrorDispatcher.java:277)
	org.apache.jasper.compiler.ErrorDispatcher.jspError(ErrorDispatcher.java:75)
	org.apache.jasper.compiler.TagLibraryInfoImpl.generateTldResourcePath(TagLibraryInfoImpl.java:250)
	org.apache.jasper.compiler.TagLibraryInfoImpl.<init>(TagLibraryInfoImpl.java:125)
	org.apache.jasper.compiler.Parser.parseTaglibDirective(Parser.java:421)
	org.apache.jasper.compiler.Parser.parseDirective(Parser.java:479)
	org.apache.jasper.compiler.Parser.parseElements(Parser.java:1435)
	org.apache.jasper.compiler.Parser.parse(Parser.java:139)
	org.apache.jasper.compiler.ParserController.doParse(ParserController.java:227)
	org.apache.jasper.compiler.ParserController.parse(ParserController.java:100)
	org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:199)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
	org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
	org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:585)
	org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:363)
	org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:396)
	org.apache.jasper.servlet.JspServlet.service(JspServlet.java:340)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
note The full stack trace of the root cause is available in the Apache Tomcat/8.0.37 logs.

--------------------------------------------------------------------------------

**Comment by RianTavares** [comment]
Estou enfrentando o mesmo problema

**Comment by luanvilarim** [comment]
Eu também

**Comment by OliveiraNt** [comment]
Vou explicar aqui o passo-a-passo que funcionou para mim:

Vai na pasta do projeto,
vai em webdep -> .settings
encontre o arquivo  "org.eclipse.wst.common.project.facet.core.xml"
abra com o bloco de notas
na linha  "<installed facet="jst.web" version="3.1"/>"
substitua o "3.0" ou "3.1"  por "2.5"
salva o arquivo
vai no eclipse
clica com o botão direito do mouse no projeto
vai em Properties (Ultima opção)
 vai no menu Project Facets (14ª opção no meu eclipse)
em Web Dynamic Project troque a versão para "2.5" se ainda não estiver e de apply (mesmo se não tive precisado trocar)
de clean no projeto e depois install 
a partir daqui se você é religioso pode rezar, se não é um café pode ajudar =)

**Comment by drinith** [comment]
Fiz esse passo a passo, mas aqui parece que continua o problema, alguém descobriu alguma coisa ? O problema só está ocorrendo mais com que está usando windows ?
