### ISSUE TITLE
install maven

### ISSUE THREAD

**Issue by drinith** [diogosmendonca/webdep#8]
Estou trazendo o projeto de novo para o eclipse zerado e quando tento dar um install no marven está retornando isso.

[ERROR] Failed to parse plugin descriptor for org.apache.maven.plugins:maven-compiler-plugin:3.1 (C:\Users\Felipe\.m2\repository\org\apache\maven\plugins\maven-compiler-plugin\3.1\maven-compiler-plugin-3.1.jar): invalid LOC header (bad signature) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginDescriptorParsingException

**Comment by diogosmendonca** [comment]
Entre o Felipe e o .m2 deveria ter uma barra (C:\Users\Felipe.m2\
repository\org\apache\maven\plugins\maven-compiler-plugin\
3.1\maven-compiler-plugin-3.1.jar) agora como configura isto tem que
pesquisar. Variáveis de ambiente podem ajudar.

Abs,

Diogo.

2016-11-20 13:29 GMT-02:00 Felipe Mello notifications@github.com:

**Comment by drinith** [comment]
Olá professor resolvi fazer tudo em outra máquina aqui e trouxe no marven
 seguinte erro

Could not transfer artifact net.sourceforge.htmlunit:neko-htmlunit:jar:2.23
from/to central (https://repo.maven.apache.org/maven2): C:\Users\Aline
Ribeiro.m2\repository\net\sourceforge\htmlunit\neko-htmlunit\2.23\aether-ae35521f-dc44-4155-9672-f382b424bdbb-neko-htmlunit-2.23.jar-in-progress
(O sistema não pode encontrar o arquivo especificado)

org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer
artifact net.sourceforge.htmlunit:neko-htmlunit:jar:2.23 from/to central (
https://repo.maven.apache.org/maven2): C:\Users\Aline
Ribeiro.m2\repository\net\sourceforge\htmlunit\neko-htmlunit\2.23\aether-ae35521f-dc44-4155-9672-f382b424bdbb-neko-htmlunit-2.23.jar-in-progress
(O sistema não pode encontrar o arquivo especificado)
at
io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:895)
at
io.takari.aether.connector.AetherRepositoryConnector$2.wrap(AetherRepositoryConnector.java:1)
at
io.takari.aether.connector.AetherRepositoryConnector$GetTask.flush(AetherRepositoryConnector.java:673)
at
io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:310)
at
org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:520)
at
org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
at
org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
at
org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
at
org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:205)
at
org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:215)
at
org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:188)
at
org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:119)
at
org.eclipse.m2e.core.internal.embedder.MavenImpl.readMavenProject(MavenImpl.java:636)
at
org.eclipse.m2e.core.internal.project.registry.DefaultMavenDependencyResolver.resolveProjectDependencies(DefaultMavenDependencyResolver.java:63)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refreshPhase2(ProjectRegistryManager.java:530)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:492)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager$3.call(ProjectRegistryManager.java:1)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:496)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.refresh(ProjectRegistryManager.java:351)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob$1$1.call(ProjectRegistryRefreshJob.java:89)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob$1$1.call(ProjectRegistryRefreshJob.java:1)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
at
org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1351)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob$1.call(ProjectRegistryRefreshJob.java:87)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob$1.call(ProjectRegistryRefreshJob.java:1)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
at
org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:99)
at
org.eclipse.m2e.core.internal.embedder.MavenImpl.execute(MavenImpl.java:1355)
at
org.eclipse.m2e.core.internal.project.registry.ProjectRegistryRefreshJob.run(ProjectRegistryRefreshJob.java:81)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: java.io.FileNotFoundException: C:\Users\Aline
Ribeiro.m2\repository\net\sourceforge\htmlunit\neko-htmlunit\2.23\aether-ae35521f-dc44-4155-9672-f382b424bdbb-neko-htmlunit-2.23.jar-in-progress
(O sistema não pode encontrar o arquivo especificado)
at java.io.FileInputStream.open0(Native Method)
at java.io.FileInputStream.open(Unknown Source)
at java.io.FileInputStream.<init>(Unknown Source)
at
org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:148)
at
org.eclipse.aether.internal.impl.DefaultFileProcessor.copy(DefaultFileProcessor.java:136)
at
org.eclipse.aether.internal.impl.DefaultFileProcessor.move(DefaultFileProcessor.java:211)
at
io.takari.aether.connector.AetherRepositoryConnector$GetTask.rename(AetherRepositoryConnector.java:677)
at
io.takari.aether.connector.AetherRepositoryConnector$GetTask.run(AetherRepositoryConnector.java:466)
at
io.takari.aether.connector.AetherRepositoryConnector.get(AetherRepositoryConnector.java:304)
... 31 more

2016-11-20 14:59 GMT-02:00 Diogo Silveira Mendonça <notifications@github.com

**Comment by drinith** [comment]
Olá Professor,
eu montei de novo a estrutura de um projeto Maven usando seus parâmetros,
recopiei tudo acho que só esse facet do persistence que não consegui montar
igual, mas ele passou a conseguir rodar sem a falha .

2016-11-20 16:29 GMT-02:00 Felipe Mello felpmel@gmail.com:
